foreground         #c7cbc9
background         #21302a
background_opacity 1.0
cursor             #c7cbc9

active_tab_foreground     #21302a
active_tab_background     #c7cbc9
inactive_tab_foreground   #c7cbc9
inactive_tab_background   #21302a

active_border_color   #c7cbc9
inactive_border_color #21302a
bell_border_color     #CFB3B2

color0       #21302a
color8       #677e75
color1       #CFB3B2
color9       #CFB3B2
color2       #AFB1D2
color10      #AFB1D2
color3       #A6B0DA
color11      #A6B0DA
color4       #C8BBCE
color12      #C8BBCE
color5       #CEC8D6
color13      #CEC8D6
color6       #D3D3EC
color14      #D3D3EC
color7       #c7cbc9
color15      #c7cbc9
