["user-password.age"]
publicKeys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO3P9h0SXWlmzjxF9K9pDEzf6PefszhZ6IQmWXX4Jfwl cicada@terminal"]

["wifi-home.age"]
publicKeys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO3P9h0SXWlmzjxF9K9pDEzf6PefszhZ6IQmWXX4Jfwl cicada@terminal"]

["gpg-private-key.age"]
publicKeys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO3P9h0SXWlmzjxF9K9pDEzf6PefszhZ6IQmWXX4Jfwl cicada@terminal"]
